name: Dependabot auto-merge

on:
  pull_request_target:
    branches:
      - master

jobs:
  auto-approve-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: major
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
